name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Setup Java
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: 'maven'
          - name: Setup Testcontainers Cloud Client
            uses: atomicjar/testcontainers-cloud-setup-action@main
            with:
              token: ${{ secrets.TCC_SECRET_EXAMPLES }}
          - name: Run example
            run: |
              ./mvnw verify
